apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: mybackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mybackend
  template:
    metadata:
      labels:
        app: mybackend  # ✅ Correspond à matchLabels
    spec:
      containers:
      - name: backend
        image: babs32/projetfilrouge_backend  # Remplacez par l'image de votre backend
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_NAME
          value: "mydb"
        - name: DB_SSLMODE
          value: "disable"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: mybackend  # ✅ doit aussi correspondre au label du pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: "mydb"
        ports:
        - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
