- name: Déploiement fullstack sur Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Déployer les secrets
      command: kubectl apply -f ../k8s/postgres-secret.yaml

    - name: Déployer la base de données PostgreSQL
      command: kubectl apply -f ../k8s/postgres-deployment.yaml

    - name: Déployer le backend
      command: kubectl apply -f ../k8s/backend-deployment.yaml

    - name: Déployer le frontend
      command: kubectl apply -f ../k8s/frontend-deployment.yaml
